### ISSUE TITLE
Converting openconfig-network-instance-l2.yang results in no CSDL file

### ISSUE THREAD

**Issue by jcleung5549** [DMTF/YANG-to-Redfish-Converter#20] opened 2018-05-23 15:39 UTC
The console does not display the "Success writing..." message.  After a short while, the console prompt is displayed.
```
$ pyang --plugindir ./YANG-to-Redfish-Plugin --format redfish --path ./yangs --target_dir testdir yangs/openconfig-netw
ork-instance-l2.yang
$
```
No file appears in the target directory.

**Comment by jcleung5549** [comment] 2018-05-23 15:43
The YANG file
[openconfig-network-instance-l2.yang.txt](https://github.com/DMTF/YANG-to-Redfish-Converter/files/2031777/openconfig-network-instance-l2.yang.txt)

**Comment by tomasg2012** [comment] 2018-05-23 15:51
This particular file uses 'submodule' which is currently unsupported, and not sure how it should be supported.  In regards to the other files in recent issues, 'grouping' is currently unsupported as well.  

Currently working on it today and tomorrow.  Would submodule be just treated like a module is in the current context?  I don't know how in particular it would connect to a main module or be referenced.  

Would a 'grouping' become a new file that is not necessarily referenced in the file it is created, perhaps just as a YangType annotation?  As in, it would generate a file for the grouping such that other, extraneous CSDL files could import and use?

**Comment by jlwhite** [comment] 2018-06-18 23:33
References are from https://tools.ietf.org/html/rfc6020

Grouping is essential to yang and used extensively with OpenConfig models. 
•	The c analogy is struct where grouping defines a set of model structure elements to drop in any place where uses refers to the defined type. 
4.2.6.  Reusable Node Groups (grouping)
   Groups of nodes can be assembled into reusable collections using the
   "grouping" statement.  A grouping defines a set of nodes that are
   instantiated with the "uses" statement
7.11.  The grouping Statement
   The "grouping" statement is used to define a reusable block of nodes,
   which may be used locally in the module, in modules that include it,
   and by other modules that import from it, according to the rules in
   Section 5.5.  It takes one argument, which is an identifier, followed
   by a block of substatements that holds detailed grouping information.

   The "grouping" statement is not a data definition statement and, as
   such, does not define any nodes in the schema tree.

   A grouping is like a "structure" or a "record" in conventional
   programming languages.



Submodule is a way to break a larger module up into component files
•	The c analogy is somewhat like #include ‘x.c’ where the submodule is to be pulled in whole as though it were part of the original file using the yang include statement
o	Note import has a similar action where the difference is import pulls in modules and many different yang modules can import a common module for say common definitions where include is just a convenience 

5.1.  Modules and Submodules
   The module is the base unit of definition in YANG.  A module defines
   a single data model.  A module can define a complete, cohesive model,
   or augment an existing data model with additional nodes.

   Submodules are partial modules that contribute definitions to a
   module.  A module may include any number of submodules, but each
   submodule may belong to only one module.
                  ….
                  ….
   A module uses the "include" statement to include its submodules, and
   the "import" statement to reference external modules.  Similarly, a
   submodule uses the "import" statement to reference other modules, and
   uses the "include" statement to reference other submodules within its
   module.  A module or submodule MUST NOT include submodules from other
   modules, and a submodule MUST NOT import its own module.

7.1.5.  The import Statement

   The "import" statement makes definitions from one module available
   inside another module or submodule.  The argument is the name of the
   module to import, and the statement is followed by a block of
   substatements that holds detailed import information.  

7.1.6.  The include Statement

   The "include" statement is used to make content from a submodule
   available to that submodule's parent module, or to another submodule
   of that parent module.  The argument is an identifier that is the
   name of the submodule to include.  Modules are only allowed to
   include submodules that belong to that module, as defined by the
   "belongs-to" statement (see Section 7.2.2).  Submodules are only
   allowed to include other submodules belonging to the same module.

   When a module includes a submodule, it incorporates the contents of
   the submodule into the node hierarchy of the module.  When a
   submodule includes another submodule, the target submodule's
   definitions are made available to the current submodule.

**Comment by jcleung5549** [comment] 2018-07-20 15:21
Running the latest changes genreates 25 CSDL files.

The following messages were displayed:

```
$ pyang --plugindir ./YANG-to-Redfish-Plugin --format redfish --target_dir output_dir/openconfig-network-instance-l2 ya
ngs/openconfig-network-instance-l2.yang
yangs/openconfig-network-instance-l2.yang:9: error: module "openconfig-extensions" not found in search path
yangs/openconfig-network-instance-l2.yang:10: error: module "openconfig-interfaces" not found in search path
We don't recognize keyword, create as statement
```

**Comment by tomasg2012** [comment] 2018-08-24 18:45
Resolution with Network TF Meeting 8/24:  Closing issue, and a new issue should be generated if the output is not as intended.

**Closed as completed by tomasg2012** 2018-08-24 18:45 UTC
