### ISSUE TITLE
Converting openconfig_if_aggregate.yang results in a single CSDL file

### ISSUE THREAD

**Issue by jcleung5549** [DMTF/YANG-to-Redfish-Converter#18] opened 2018-05-23 15:29 UTC
The console message indicates no problems
```
$ pyang --plugindir ./YANG-to-Redfish-Plugin --format redfish --path ./yangs --target_dir testdir yangs/openconfig-if-a
ggregate.yang
Success writing file to disk: testdir/openconfig_if_aggregate_v1.xml
```
But the resultant file has minimal content.

[openconfig_if_aggregate_v1.xml.txt](https://github.com/DMTF/YANG-to-Redfish-Converter/files/2031711/openconfig_if_aggregate_v1.xml.txt)

**Comment by jcleung5549** [comment] 2018-05-23 15:44
The YANG file
[openconfig-if-aggregate.yang.txt](https://github.com/DMTF/YANG-to-Redfish-Converter/files/2031781/openconfig-if-aggregate.yang.txt)

**Comment by jcleung5549** [comment] 2018-07-20 15:11
7/20 Running the latest changes generated 8 CSDL files.

The following messages were displayed.

```
$ pyang --plugindir ./YANG-to-Redfish-Plugin --format redfish --target_dir output_dir/openconfig-if-aggregate yangs/ope
nconfig-if-aggregate.yang
yangs/openconfig-if-aggregate.yang:11: error: module "openconfig-interfaces" not found in search path
yangs/openconfig-if-aggregate.yang:12: error: module "openconfig-if-ethernet" not found in search path
yangs/openconfig-if-aggregate.yang:12: warning: imported module openconfig-if-ethernet not used
yangs/openconfig-if-aggregate.yang:14: error: module "openconfig-if-types" not found in search path
yangs/openconfig-if-aggregate.yang:15: error: module "openconfig-extensions" not found in search path
We don't recognize keyword, create as statement
```

**Comment by tomasg2012** [comment] 2018-08-24 18:44
Resolution with Network TF Meeting 8/24:  Closing issue, and a new issue should be generated if the output is not as intended.

**Closed as completed by tomasg2012** 2018-08-24 18:44 UTC
