### ISSUE TITLE
Converting openconfig_vlan.yang results in a single CSDL file

### ISSUE THREAD

**Issue by jcleung5549** [DMTF/YANG-to-Redfish-Converter#19] opened 2018-05-23 15:34 UTC
The console message indicates no problems
```
$ pyang --plugindir ./YANG-to-Redfish-Plugin --format redfish --path ./yangs --target_dir testdir yangs/openconfig-vlan
.yang
Success writing file to disk: testdir/openconfig_vlan_v1.xml
```
But the resultant file has minimal content.
[openconfig_vlan_v1.xml.txt](https://github.com/DMTF/YANG-to-Redfish-Converter/files/2031738/openconfig_vlan_v1.xml.txt)

**Comment by jcleung5549** [comment] 2018-05-23 15:45
The YANG file
[openconfig-vlan.yang.txt](https://github.com/DMTF/YANG-to-Redfish-Converter/files/2031787/openconfig-vlan.yang.txt)

**Comment by jcleung5549** [comment] 2018-07-20 15:06
7/20 Running latest changes generates 36 CSDL files.

However, the following messages were displayed.  I think there was a way to set the search path.

```
$ pyang --plugindir ./YANG-to-Redfish-Plugin --format redfish yangs/openconfig-vlan.yang
yangs/openconfig-vlan.yang:11: error: module "openconfig-vlan-types" not found in search path
yangs/openconfig-vlan.yang:12: error: module "openconfig-interfaces" not found in search path
yangs/openconfig-vlan.yang:13: error: module "openconfig-if-ethernet" not found in search path
yangs/openconfig-vlan.yang:13: warning: imported module openconfig-if-ethernet not used
yangs/openconfig-vlan.yang:14: error: module "openconfig-if-aggregate" not found in search path
yangs/openconfig-vlan.yang:14: warning: imported module openconfig-if-aggregate not used
yangs/openconfig-vlan.yang:16: error: module "openconfig-extensions" not found in search path
We don't recognize keyword, create as statement
```

**Comment by tomasg2012** [comment] 2018-08-24 18:45
Resolution with Network TF Meeting 8/24:  Closing issue, and a new issue should be generated if the output is not as intended.

**Closed as completed by tomasg2012** 2018-08-24 18:45 UTC
