### ISSUE TITLE
'Unrecognized keyword' message during openconfig model conversion

### ISSUE THREAD

**Issue by vsawal** [DMTF/YANG-to-Redfish-Converter#30] opened 2018-11-02 02:31 UTC
On `yang-plugin` branch, receiving following notification while converting [https://github.com/openconfig/public/blob/master/release/models/vlan/openconfig-vlan-types.yang](url) file:
```
(py3) vsawal@W109PQB7H2:~/dmtf/YANG-to-Redfish-Converter$ pyang --plugindir ./YANG-to-Redfish-Plugin --format redfish --
path ~/dmtf/public --target_dir ~/dmtf/yang_to_rf_csdl/ ~/dmtf/public/release/models/vlan/openconfig-vlan-types.yang
We don't recognize keyword ('openconfig-extensions', 'openconfig-version'), create as statement
new TYPE:: vlan-id
new TYPE:: vlan-range
new TYPE:: qinq-id
new TYPE:: qinq-id-range
new TYPE:: vlan-mode-type
new TYPE:: vlan-ref
Success writing file to disk: /home/vsawal/dmtf/yang_to_rf_csdl//openconfig_vlan_types_v1.xml
(py3) vsawal@W109PQB7H2:~/dmtf/YANG-to-Redfish-Converter$
```

**Comment by tomasg2012** [comment] 2018-11-08 22:47
Should probably move these outputs to a logger.  In the meantime, that is intended behavior for the plug-in according to the scope of the specification of YANG to Redfish, it simply makes a generic statement of that kind of information.

**Comment by mraineri** [comment] 2019-02-28 21:53
Resolved in latest PR

**Closed as completed by mraineri** 2019-02-28 21:53 UTC
